apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: kubeflow
  namespace: kubeflow
spec:
  applications:
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: openshift-operators
        repoRef:
          name: odhmanifests
          path: openshift-service-mesh/base
      name: openshift-sm
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/openshift/openshift-scc/overlays/servicemesh
      name: openshift-scc
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/cert-manager
      name: cert-manager
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/admission-webhook/overlays/servicemesh
      name: admission-webhook
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/openshift-service-mesh
      name: istio-service-mesh
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/knative/overlays/servicemesh
      name: knative
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/kfserving/overlays/servicemesh
      name: kfserving
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/jupyter-web-app/overlays/servicemesh
      name: jupyter-web-app
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/notebook-controller/overlays/servicemesh
      name: notebook-controller
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/centraldashboard/overlays/servicemesh
      name: centraldashboard
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/volumes-web-app/overlays/servicemesh
      name: volumes-web-app
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/pytorch-job/overlays/servicemesh
      name: pytorch-job
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/tf-job/overlays/servicemesh
      name: tf-job
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/katib/overlays/servicemesh
      name: katib
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift/application/kfp-tekton/overlays/servicemesh
      name: kfp-tekton
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: distributions/stacks/openshift
      name: kubeflow-apps
  repos:
    - name: odhmanifests
      uri: https://github.com/opendatahub-io/odh-manifests/tarball/master
    - name: manifests
      uri: https://github.com/opendatahub-io/manifests/archive/v1.3-openshift.tar.gz
  version: v1.3.0-tag
