apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
   - ../../base
   - virtual-service.yaml
   - network_policy.yaml

patchesJson6902:
   - path: ../../../../add_label.yaml
     target:
        group: apps
        version: v1
        kind: Deployment
        name: metadata-envoy-deployment
   - path: ../../../../add_label.yaml
     target:
        group: apps
        version: v1
        kind: Deployment
        name: tekton-pipelineloop-controller
        namespace: tekton-pipelines
   - path: ../../../../add_label.yaml
     target:
        group: apps
        version: v1
        kind: Deployment
        name: tekton-pipelineloop-webhook
        namespace: tekton-pipelines
   - path: ../../../../add_label.yaml
     target:
        group: apps
        version: v1
        kind: Deployment
        name: tekton-pipelines-controller
        namespace: tekton-pipelines
   - path: ../../../../add_label.yaml
     target:
        group: apps
        version: v1
        kind: Deployment
        name: tekton-pipelines-webhook
        namespace: tekton-pipelines
